name: Deployment

on:
  push:
    branches: [ task/pipeline_copy ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.200'

      - name: Display .NET version
        run: dotnet --version

      - name: Install dependencies
        run: |
          dotnet restore webapi/webapi.csproj
          dotnet restore webapi.test/webapi.test.csproj

      - name: Build
        run: |
          dotnet build --no-restore webapi/webapi.csproj
          dotnet build --no-restore webapi.test/webapi.test.csproj


      - name: Docker test
        run: |
          docker --version
          docker pull amazon/dynamodb-local
          docker run -d -p 8001:8000 --name dynamodb-local amazon/dynamodb-local -jar DynamoDBLocal.jar -sharedDb

      - name: Run tests
        run: |
          dotnet test --no-build --verbosity normal --logger trx --collect "Code coverage" webapi.test/webapi.test.csproj
          if [ $? -ne 0 ]; then
            echo "Tests failed. Printing test results:"
            dotnet test --no-build --verbosity normal --logger console --collect "Code coverage" webapi.test/webapi.test.csproj
          fi
          
      - name: Publish General Tests
        uses: actions/dorny_test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: GeneralTests
          path: "**/TestResultsGeneralTests.trx"
          reporter: dotnet-trx
          fail-on-error: false




        env:
          AWS_ACCESS_KEY_ID: fakeMyKeyId
          AWS_SECRET_ACCESS_KEY: fakeSecretAccessKey
          DYNAMODB_ENDPOINT: http://localhost:8000
        continue-on-error: true