name: Deployment

on:
  push:
    branches: [ task/pipeline_copy ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.200'

      - name: Display .NET version
        run: dotnet --version

      - name: Install dependencies
        run: |
          dotnet restore webapi/webapi.csproj
          dotnet restore webapi.test/webapi.test.csproj
          
      - name: Clean the project
        run: dotnet clean

      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v4.0.0
        with:
          port: 8000
          cors: '*'
          sharedDb: false
        
      - name: Verify DynamoDB Local is running
        run: |
          docker ps -a | grep dynamodb-local
          echo "Waiting for DynamoDB Local to start..."
          sleep 10
          curl -X POST http://localhost:8080 -H "Content-Type: application/x-amz-json-1.0" \
          -d '{"TableName":"TestTable"}'

      - name: Run tests
        run: |
          dotnet test --no-build --verbosity normal --logger trx --collect "Code coverage" webapi.test/webapi.test.csproj
          if [ $? -ne 0 ]; then
            echo "Tests failed. Printing test results:"
            dotnet test --no-build --verbosity normal --logger console --collect "Code coverage" webapi.test/webapi.test.csproj
          fi
        env:
          DYNAMODB_ENDPOINT: http://localhost:8000
        continue-on-error: false