name: Deployment

on:
  push:
    branches: [ test-jan ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: user/app:latest
      -
        name: Start DynamoDB
        run: |
          docker run -d --name dynamodb -p 8000:8000 amazon/dynamodb-local
          sleep 15
          docker ps
          docker logs dynamodb
      -
        name: Verify DynamoDB connection
        run: |
          echo "Verbindungstest zu DynamoDB..."
          curl http://localhost:8000
      -
        name: Run tests
        run: |
          dotnet test --no-build --verbosity normal --logger trx --collect "Code coverage" webapi.test/webapi.test.csproj
          if [ $? -ne 0 ]; then
            echo "Tests failed. Printing test results:"
            dotnet test --no-build --verbosity normal --logger console --collect "Code coverage" webapi.test/webapi.test.csproj
          fi
        env:
          DYNAMODB_ENDPOINT: http://localhost:8000
        continue-on-error: true