name: Deployment

on:
  push:
    branches: [ test-jan ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.200'

      - name: Display .NET version
        run: dotnet --version

      - name: Install dependencies
        run: |
          dotnet restore webapi/webapi.csproj
          dotnet restore webapi.test/webapi.test.csproj

      - name: Build
        run: |
          dotnet build --no-restore webapi/webapi.csproj
          dotnet build --no-restore webapi.test/webapi.test.csproj

      - name: Start DynamoDB
        run: |
          docker run -d --name dynamodb -p 8000:8000 amazon/dynamodb-local
          sleep 15

      - name: Verify DynamoDB connection
        run: |
          echo "Verbindungstest zu DynamoDB..."
          curl http://localhost:8000

      - name: Run tests
        run: |
          dotnet test --no-build --verbosity normal --logger trx --collect "Code coverage" webapi.test/webapi.test.csproj
          if [ $? -ne 0 ]; then
            echo "Tests failed. Printing test results:"
            dotnet test --no-build --verbosity normal --logger console --collect "Code coverage" webapi.test/webapi.test.csproj
          fi
        env:
          DYNAMODB_ENDPOINT: http://localhost:8000
        continue-on-error: true