name: Deployment

on:
  push:
    branches: [ task/pipeline_copy ]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.200'

      - name: Display .NET version
        run: dotnet --version
      
      - name: Install dependencies
        run: |
          dotnet restore webapi/webapi.csproj
          dotnet restore webapi.test/webapi.test.csproj
          
      - name: Clean the project
        run: dotnet clean

      #- name: Build
      #  run: |
      #    dotnet build --no-restore webapi/webapi.csproj
      #    dotnet build --no-restore webapi.test/webapi.test.csproj

      #- name: Setup DynamoDB Local
      #  uses: rrainn/dynamodb-action@v2.0.1
      #  with:
      #    port: 8000
      #    cors: '*'

#      - name: Setup DynamoDB Local
#        run: docker run -d -p 8000:8000 amazon/dynamodb-local:latest
#        env:
#          AWS_ACCESS_KEY_ID: fakeMyKeyId
#          AWS_SECRET_ACCESS_KEY: fakeSecretAccessKey

      - name: Verify DynamoDB Local is running
        run: |
          docker ps -a | grep dynamodb-local

      - name: Run tests
        run: |
          dotnet test --no-build --verbosity normal --logger trx --collect "Code coverage" webapi.test/webapi.test.csproj
          if [ $? -ne 0 ]; then
            echo "Tests failed. Printing test results:"
            dotnet test --no-build --verbosity normal --logger console --collect "Code coverage" webapi.test/webapi.test.csproj
          fi
        env:
          DYNAMODB_ENDPOINT: http://localhost:8000
        continue-on-error: false