name: Deployment

on:
  push:
    branches: [ task/pipeline_copy ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.200'

      - name: Display .NET version
        run: dotnet --version

      - name: Install dependencies
        run: |
          dotnet restore webapi/webapi.csproj
          dotnet restore webapi.test/webapi.test.csproj
          
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start DynamoDB Local using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
          echo "Waiting for DynamoDB Local to start..."
          sleep 15 # Ajustar tiempo según sea necesario
          docker-compose logs dynamodb-local

      - name: Verify DynamoDB Local is running
        run: |
          docker ps -a | grep dynamodb-local
          echo "Waiting for DynamoDB Local to respond..."
          curl -X POST http://localhost:8000 \
            -H "Content-Type: application/x-amz-json-1.0" \
            -H "X-Amz-Target: DynamoDB_20120810.ListTables" \
            -H "Authorization: AWS4-HMAC-SHA256 Credential=DUMMYIDEXAMPLE/20250318/us-west-2/dynamodb/aws4_request, SignedHeaders=content-type;host;x-amz-target, Signature=DUMMYEXAMPLEKEY" \
            -H "X-Amz-Date: 20250318T000000Z" \
            -d '{}'
            --max-time 10 || (echo "DynamoDB Local is not responding" && exit 1)

      - name: Run tests
        run: |
          dotnet test --no-build --verbosity normal --logger trx --collect "Code coverage" webapi.test/webapi.test.csproj
          if [ $? -ne 0 ]; then
            echo "Tests failed. Printing test results:"
            dotnet test --no-build --verbosity normal --logger console --collect "Code coverage" webapi.test/webapi.test.csproj
          fi
        env:
          DYNAMODB_ENDPOINT: http://localhost:8000
        continue-on-error: false