name: Deployment

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Display .NET version
        run: dotnet --version

      - name: Install dependencies
        run: dotnet restore testProject/testProject.csproj

      - name: Build
        run: dotnet build --no-restore testProject/testProject.csproj

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName~DynamoDbTests testProject/testProject.csproj
        env:
          DYNAMODB_ENDPOINT: http://dynamodb:8000