name: Deployment

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.200'

      - name: Display .NET version
        run: dotnet --version

      - name: Install dependencies
        run: |
          dotnet restore webapi/webapi.csproj
          dotnet restore webapi.test/webapi.test.csproj

      - name: Build
        run: |
          dotnet build --no-restore webapi/webapi.csproj
          dotnet build --no-restore webapi.test/webapi.test.csproj

      - name: Set up Docker Buildx
        id: buildx
        run: |
          docker buildx create --name mybuilder --driver docker-container --bootstrap
          docker buildx use mybuilder
          docker buildx inspect --bootstrap

      - name: Start DynamoDB
        run: |
          docker pull amazon/dynamodb-local
          docker run -d --name dynamodb --network host amazon/dynamodb-local -jar DynamoDBLocal.jar -sharedDb -inMemory -noVerifySSL

      - name: Verify DynamoDB connection
        run: |
          # Warte 15 Sekunden, damit DynamoDB Zeit hat, vollst채ndig zu starten
          sleep 15
          # F체hre einen manuellen Test durch, um die DynamoDB-Verbindung zu 체berpr체fen
          curl http://localhost:8000

      - name: Run tests
        run: |
          dotnet test --no-build --verbosity normal --logger trx --collect "Code coverage" webapi.test/webapi.test.csproj
          if [ $? -ne 0 ]; then
            echo "Tests failed. Printing test results:"
            dotnet test --no-build --verbosity normal --logger console --collect "Code coverage" webapi.test/webapi.test.csproj
          fi
        env:
          DYNAMODB_ENDPOINT: http://localhost:8000
        continue-on-error: true